#!/usr/bin/env python3
"""Slice 58 — stitched end-to-end validation for the single-figure visual pilot.

This is a *validation/harness* slice. It adds NO production behavior: it proves the
already-shipped Slices 52–57 single-figure pilot works as one connected chain before
any visual expansion is considered. Nothing here changes insertion, rendering, export,
extraction/OCR routing, prompts, or the API surface.

The chain it stitches (each stage feeds the next):

    safe job-local assets/<slug>.png
      -> existing visual manifest / replacement-plan shape
      -> global pilot master flag ON (env)
      -> per-job opt-in ON
      -> standard markdown image insertion (exactly one figure)
      -> HTML / PDF / DOCX render compatibility
      -> export ZIP portability including the single referenced PNG

Boundaries honoured (no expansion): exactly one figure, no multi-figure, no Chandra /
Mistral / Gemini / cloud OCR, no model/provider/llama-server calls, no new image
pipeline, no renderer rewrite, no prompt/extraction/export behavior change, no new API
route, no committed binary/image fixtures.

Data discipline: every PNG/PDF/DOCX/HTML/ZIP is synthetic and written under a temp
dir at runtime, never committed. The test PNG is generated by a tiny stdlib builder
(zlib + struct) — not a committed file, not base64, not a data URI. No raw image bytes,
host paths, tokens, Authorization headers, raw argv, model/mmproj/executable paths,
provider payloads, OCR dumps, or full URLs are ever printed or asserted on. A final
no-leak sweep scans every serialized output the harness produced.

Host-only runs SKIP the renderer (Chromium / python-docx / markdown-it) and the export
(FastAPI) sections cleanly when those deps are absent; run inside the container for the
full chain. See docs/VISUAL_PILOT_E2E_VALIDATION.md.

Run:

    python test_scripts/test_visual_pilot_e2e_validation.py
"""
from __future__ import annotations

import io
import json
import os
import re
import struct
import sys
import tempfile
import zipfile
import zlib
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from pipeline import visual_markdown_insertion as vmi  # noqa: E402

PASS = 0
FAIL = 0
SKIP = 0

# Every serialized output the harness produces is appended here, then swept once at the
# end for any of the forbidden value shapes. A stage that forgets its own leak check is
# still caught by this backstop.
OUTPUTS: list[str] = []

# --- Forbidden value shapes (no-leak sweep) ---------------------------------------
KEYLIKE = re.compile(r"(sk-|sk_|pk-|rk_)[A-Za-z0-9_\-]{12,}")
PATHLIKE = re.compile(r"(/home/|/usr/|/etc/|/var/|/root/|/opt/|C:\\|\\\\)")
URLLIKE = re.compile(r"https?://|file://|ftp://")
AUTHLIKE = re.compile(r"Authorization|Bearer\s+\S", re.IGNORECASE)
SOCKETLIKE = re.compile(r"\.sock\b")
DATAURI = re.compile(r"data:[^;]+;base64,", re.IGNORECASE)
GGUFLIKE = re.compile(r"\.gguf\b|mmproj|\.bin\b|llama-server", re.IGNORECASE)
ARGVLIKE = re.compile(r"--\w+\s+\S")

_LEAK_PATTERNS = (
    ("key", KEYLIKE), ("path", PATHLIKE), ("url", URLLIKE), ("auth", AUTHLIKE),
    ("socket", SOCKETLIKE), ("datauri", DATAURI), ("gguf", GGUFLIKE), ("argv", ARGVLIKE),
)

# A recognisable ASCII marker baked into the synthetic PNG body. It must ride along in a
# zipped image entry (proving the export works) but must NEVER appear in a bundle index,
# markdown, html, or any other serialized string the harness inspects.
PNG_BODY_SENTINEL = "png_image_body_sentinel"

# Production manifest captions are normally ``None``, which yields the generic
# page-derived caption — that real path is what verification #3 asserts.

SLUG = "s00_page_0003_figure_01"
ASSET = f"{SLUG}.png"
ASSET_REF = f"assets/{ASSET}"
PAGE = 3
GENERIC_CAPTION = f"Extracted figure from source page {PAGE}"

BASE_MD = "# Synthetic Guide\n\nSome content.\n"


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS, FAIL
    if condition:
        PASS += 1
        print(f"[PASS] {name}")
    else:
        FAIL += 1
        print(f"[FAIL] {name}" + (f" — {detail}" if detail else ""))


def skip(name: str, detail: str = "") -> None:
    global SKIP
    SKIP += 1
    print(f"[SKIP] {name}" + (f" — {detail}" if detail else ""))


def record(text: str) -> str:
    """Stash a serialized output for the final no-leak sweep and return it unchanged."""
    if isinstance(text, str):
        OUTPUTS.append(text)
    return text


# --- Synthetic PNG builder (stdlib only; no committed fixture, no base64) ----------
def build_png(width: int = 2, height: int = 2) -> bytes:
    """A tiny but valid 8-bit grayscale PNG, built at runtime with zlib + struct.

    The ``PNG_BODY_SENTINEL`` marker is appended after IEND so the export ride-along has
    a recognisable body to detect, without ever embedding a path/secret. The bytes are
    never printed or asserted on directly (only membership/length/equality).
    """
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0)
    raw = b"".join(b"\x00" + b"\xff" * width for _ in range(height))  # filter byte + row
    idat = zlib.compress(raw, 9)
    body = sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")
    return body + PNG_BODY_SENTINEL.encode("ascii")


PNG_BYTES = build_png()


# --- Duck-typed job for the insertion + render chain (no FastAPI needed) -----------
@dataclass
class FakeJob:
    dir: Path
    opt_in: bool = True

    @property
    def visual_assets_manifest_json(self) -> Path:
        return self.dir / "visual_assets_manifest.json"

    @property
    def visual_replacement_plan_json(self) -> Path:
        return self.dir / "visual_replacement_plan.json"

    @property
    def assets_dir(self) -> Path:
        return self.dir / "assets"

    @property
    def clean_md(self) -> Path:
        return self.dir / "clean.md"

    @property
    def visual_markdown_image_pilot(self) -> bool:
        return self.opt_in


def _figure_asset(asset_id: str, *, image_ref: str, page: int = PAGE, caption=None) -> dict:
    return {
        "asset_id": asset_id,
        "source_page": page,
        "asset_type": "extracted_figure",
        "bbox": [0.0, 0.0, 10.0, 10.0],
        "caption": caption,
        "source_provider": "fitz_local",
        "image_ref": image_ref,
        "scores": {},
        "signals": {},
        "warnings": [],
    }


def _manifest(assets: list[dict]) -> dict:
    return {
        "version": 1,
        "kind": "visual_assets_manifest",
        "status": "completed",
        "source": "extraction_metadata.json",
        "assets": assets,
        "summary": {"asset_count": len(assets)},
        "warnings": [],
    }


def _plan_item(asset_id: str) -> dict:
    return {
        "asset_id": asset_id,
        "source_page": PAGE,
        "source_provider": "fitz_local",
        "asset_type": "extracted_figure",
        "priority": "high",
        "candidate_action": "candidate_include_as_figure",
        "placement": "source_page_reference",
        "reasons": ["score_high", "asset_type_figure"],
        "warnings": [],
    }


def _plan(items: list[dict]) -> dict:
    return {
        "version": 1,
        "kind": "visual_replacement_plan",
        "status": "completed",
        "source": "visual_asset_scoring.json",
        "items": items,
        "summary": {},
        "warnings": [],
    }


def _write_job(tmp: Path, *, assets: list[dict], plan_items, png_names) -> FakeJob:
    job = FakeJob(dir=tmp)
    job.assets_dir.mkdir(parents=True, exist_ok=True)
    for name in png_names:
        (job.assets_dir / name).write_bytes(PNG_BYTES)
    job.visual_assets_manifest_json.write_text(
        json.dumps(_manifest(assets)) + "\n", encoding="utf-8"
    )
    if plan_items is not None:
        job.visual_replacement_plan_json.write_text(
            json.dumps(_plan(plan_items)) + "\n", encoding="utf-8"
        )
    return job


def _force_env(value):
    old = os.environ.get(vmi.ENABLE_ENV)
    if value is None:
        os.environ.pop(vmi.ENABLE_ENV, None)
    else:
        os.environ[vmi.ENABLE_ENV] = value
    return old


def _restore_env(old) -> None:
    if old is None:
        os.environ.pop(vmi.ENABLE_ENV, None)
    else:
        os.environ[vmi.ENABLE_ENV] = old


# ---------------------------------------------------------------------------
# Stage 1 — insertion core (always runs; env master switch forced ON)
# ---------------------------------------------------------------------------
def stage_insertion(work: Path) -> str:
    """Stitch: manifest/plan/png -> flag ON -> opt-in ON -> exactly one markdown image.

    Returns the produced clean.md so the render stage can consume it (true stitch).
    Verifications 1–5.
    """
    old = _force_env("1")
    try:
        # Real production shape: manifest captions are normally None, which yields the
        # generic page-derived caption (verification #3). A dangerous-caption variant is
        # exercised separately below to prove unsafe shapes are stripped.
        job = _write_job(
            work,
            assets=[_figure_asset(SLUG, image_ref=ASSET_REF, caption=None)],
            plan_items=[_plan_item(SLUG)],
            png_names=[ASSET],
        )

        # Snapshot inputs to prove the pilot mutates neither artifacts nor the source PNG.
        man_before = job.visual_assets_manifest_json.read_text(encoding="utf-8")
        plan_before = job.visual_replacement_plan_json.read_text(encoding="utf-8")
        png_before = (job.assets_dir / ASSET).read_bytes()

        out, info = vmi.apply_visual_markdown_pilot(job, BASE_MD)
        record(out)
        record(json.dumps(info, default=str))

        # (1) exactly one image inserted, flag+opt-in both honoured.
        check("insertion.status_inserted", info.get("status") == vmi.STATUS_INSERTED, str(info))
        check("insertion.exactly_one_image", out.count("![") == 1, str(out.count("![")))

        # (2) the ref is exactly the safe relative form assets/<slug>.png.
        check("insertion.ref_is_safe_relative", f"]({ASSET_REF})" in out, out)
        check("insertion.ref_not_absolute", "/home/" not in out and "file://" not in out)

        # (3) caption is the generic page caption (the real None-caption path), not raw text.
        check("insertion.caption_generic", f"![{GENERIC_CAPTION}]" in out, out)

        # (4) an unsafe asset ref is rejected (no insertion) on an otherwise-eligible figure.
        with tempfile.TemporaryDirectory() as d2:
            bad_job = FakeJob(dir=Path(d2))
            bad_job.assets_dir.mkdir(parents=True, exist_ok=True)
            bad_job.visual_assets_manifest_json.write_text(
                json.dumps(_manifest([_figure_asset("b1", image_ref="../../../etc/passwd.png")]))
                + "\n",
                encoding="utf-8",
            )
            bad_out, bad_info = vmi.apply_visual_markdown_pilot(bad_job, BASE_MD)
            record(bad_out)
            check("insertion.unsafe_ref_rejected",
                  bad_out == BASE_MD and "![" not in bad_out, str(bad_info))
        # Also assert the pure validator still rejects the classic unsafe shapes.
        v = vmi.validate_visual_asset_ref
        check("insertion.validator_rejects_unsafe",
              v("/etc/passwd.png") is None
              and v("assets/../secret.png") is None
              and v("assets\\fig.png") is None
              and v("https://x/y.png") is None
              and v("data:image/png;base64,AAAA") is None
              and v("assets/fig.jpg") is None
              and v("assets/sub/fig.png") is None)
        check("insertion.validator_accepts_safe", v(ASSET_REF) == ASSET_REF)

        # (5) inputs unmutated: manifest, plan, and source PNG bytes are byte-identical.
        check("insertion.manifest_unmutated",
              job.visual_assets_manifest_json.read_text(encoding="utf-8") == man_before)
        check("insertion.plan_unmutated",
              job.visual_replacement_plan_json.read_text(encoding="utf-8") == plan_before)
        check("insertion.source_png_unmutated",
              (job.assets_dir / ASSET).read_bytes() == png_before)

        # Persist the produced clean.md for the render stage (the genuine pilot output).
        job.clean_md.write_text(out, encoding="utf-8")
        return out
    finally:
        _restore_env(old)


# ---------------------------------------------------------------------------
# Stage 2 — render compatibility (HTML always-ish; PDF/DOCX host-skippable)
# ---------------------------------------------------------------------------
def stage_render(work: Path) -> None:
    """Stitch: the pilot's clean.md renders to HTML/PDF/DOCX with the relative ref.

    Verifications 6–8. Renderers are NOT rewritten; missing host deps SKIP cleanly.
    """
    clean = work / "clean.md"

    # (6) HTML contains a safe relative <img src="assets/...png"> and no absolute path.
    try:
        from pipeline.html_renderer import render_markdown_file
    except Exception as exc:  # markdown-it / deps unavailable
        skip("render.html", f"renderer import unavailable ({type(exc).__name__})")
    else:
        try:
            html = record(render_markdown_file(clean))
        except Exception as exc:
            skip("render.html", f"render unavailable ({type(exc).__name__})")
        else:
            check("render.html_has_relative_img",
                  "<img" in html and f'src="{ASSET_REF}"' in html, html[:200])
            check("render.html_no_absolute_path",
                  "file://" not in html and "/home/" not in html and "/etc/" not in html)

    # (7) PDF render completes and produces a non-empty PDF; SKIP if no Chromium.
    try:
        from pipeline.pdf_renderer import render_pdf, _find_chromium
    except Exception as exc:
        skip("render.pdf", f"renderer import unavailable ({type(exc).__name__})")
    else:
        if _find_chromium() is None:
            skip("render.pdf", "no Chromium on host")
        else:
            out_pdf = work / "final.pdf"
            try:
                render_pdf(clean, out_pdf)
            except Exception as exc:
                check("render.pdf_no_raise", False, type(exc).__name__)
            else:
                check("render.pdf_nonempty", out_pdf.is_file() and out_pdf.stat().st_size > 0)
                # Slice 60: a non-empty PDF is not enough — confirm the figure is an
                # embedded image object, not a broken/alt-text-only marker. SKIP only
                # when PyMuPDF is unavailable on the host.
                try:
                    import fitz  # PyMuPDF
                except Exception as exc:
                    skip("render.pdf_image_visible", f"PyMuPDF unavailable ({type(exc).__name__})")
                else:
                    embedded = False
                    try:
                        with fitz.open(str(out_pdf)) as doc:
                            embedded = any(page.get_images(full=True) for page in doc)
                    except Exception as exc:
                        skip("render.pdf_image_visible", f"inspect unavailable ({type(exc).__name__})")
                    else:
                        check("render.pdf_image_visible", embedded)

    # (8) DOCX generation embeds or degrades without raising; SKIP if python-docx absent.
    try:
        import docx  # noqa: F401
        from pipeline.docx_renderer import render_docx
    except Exception as exc:
        skip("render.docx", f"python-docx unavailable ({type(exc).__name__})")
    else:
        out_docx = work / "final.docx"
        try:
            render_docx(clean, out_docx, title="Synthetic Guide")
        except Exception as exc:
            check("render.docx_no_raise", False, type(exc).__name__)
        else:
            check("render.docx_nonempty", out_docx.is_file() and out_docx.stat().st_size > 0)


# ---------------------------------------------------------------------------
# Stage 3 — export ZIP portability (FastAPI-skippable)
# ---------------------------------------------------------------------------
def stage_export() -> None:
    """Stitch: real Job -> pilot-produced clean.md -> export bundle carries one PNG.

    Verifications 9–12. Drives the real ``api.server.export_bundle`` against temp-dir
    Jobs (``_get_job`` monkeypatched), mirroring test_visual_pilot_export_asset.py.
    SKIPPED when FastAPI is not importable in host Python (run in Docker).
    """
    try:
        from fastapi import HTTPException

        from api import server  # noqa: WPS433
    except Exception as exc:
        skip("export.bundle", f"FastAPI unavailable ({type(exc).__name__})")
        return

    from pipeline.job_manager import Job

    EXTRA = "fig_p007_09_extra.png"

    def _make_job(root: Path, job_id: str, *, with_pdf: bool, clean_md: str,
                  assets: dict[str, bytes] | None) -> Job:
        job = Job(id=job_id, root=root)
        job.input_dir.mkdir(parents=True, exist_ok=True)
        job.logs_dir.mkdir(parents=True, exist_ok=True)
        # Opt the job in via the persisted manifest (the real per-job switch).
        job._write_manifest({
            "id": job.id, "status": "completed", "title": job.id,
            "visual_markdown_image_pilot": True,
        })
        if with_pdf:
            job.final_pdf.write_bytes(b"%PDF-1.4 synthetic pdf bytes")
        if assets:
            job.assets_dir.mkdir(parents=True, exist_ok=True)
            for name, data in assets.items():
                (job.assets_dir / name).write_bytes(data)
        job.save_text(job.clean_md, clean_md)
        return job

    def _bundle(jobs_by_id, job_ids, artifacts):
        original = server._get_job

        def fake_get_job(raw_id):
            jid = str(raw_id)
            if jid in jobs_by_id:
                return jobs_by_id[jid]
            raise HTTPException(status_code=404, detail="Job not found.")

        server._get_job = fake_get_job
        try:
            return server.export_bundle(
                server.BundleRequest(job_ids=job_ids, artifacts=artifacts)
            )
        finally:
            server._get_job = original

    # Produce clean.md through the genuine pilot so the export consumes a real chain.
    old = _force_env("1")
    try:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            seed = _make_job(
                root, "job-seed", with_pdf=True,
                clean_md=BASE_MD,
                assets={ASSET: PNG_BYTES},
            )
            # Stitch: regenerate clean.md via the pilot against this real Job.
            seed_manifest = seed.assets_dir.parent / "visual_assets_manifest.json"
            seed_manifest.write_text(
                json.dumps(_manifest([_figure_asset(SLUG, image_ref=ASSET_REF)])) + "\n",
                encoding="utf-8",
            )
            produced, info = vmi.apply_visual_markdown_pilot(seed, BASE_MD)
            record(produced)
            check("export.pilot_produced_image",
                  info.get("status") == vmi.STATUS_INSERTED and ASSET_REF in produced, str(info))
            seed.save_clean_md(produced, source="slice58_e2e")

            # Add an unreferenced extra crop alongside the referenced one.
            (seed.assets_dir / EXTRA).write_bytes(PNG_BYTES)

            resp = _bundle({"job-seed": seed}, ["job-seed"], ["pdf", "markdown"])
            with zipfile.ZipFile(io.BytesIO(resp.body)) as zf:
                names = zf.namelist()
                png_entries = [n for n in names if n.lower().endswith(".png")]
                manifest_text = record(zf.read("manifest.json").decode("utf-8"))
                png_data = zf.read(png_entries[0]) if png_entries else b""

            # (9) exactly the single referenced PNG, under the job's assets/ folder.
            check("export.exactly_one_png", len(png_entries) == 1, str(png_entries))
            check("export.png_is_referenced_asset",
                  any(n.endswith(f"/assets/{ASSET}") for n in names), str(names))
            check("export.png_under_assets_relative",
                  all("/assets/" in p and not p.startswith("/") and ".." not in p
                      and "\\" not in p for p in png_entries), str(png_entries))
            check("export.png_carries_real_bytes", png_data == PNG_BYTES)

            # (10) the unreferenced extra crop / whole assets dir are NOT bundled.
            check("export.extra_crop_excluded",
                  not any(n.endswith(f"/assets/{EXTRA}") for n in names), str(names))
            check("export.no_blanket_assets_dir", len(png_entries) <= 1, str(png_entries))

            # (12) bundle index records only the safe relative ref; no bytes/paths.
            manifest = json.loads(manifest_text)
            entry = manifest["jobs"][0]
            check("export.manifest_safe_relative_ref",
                  entry.get("visual_pilot_asset") == ASSET_REF,
                  str(entry.get("visual_pilot_asset")))
            check("export.manifest_no_image_bytes", PNG_BODY_SENTINEL not in manifest_text)
            check("export.manifest_no_leak", _sweep_one(manifest_text) is None,
                  _sweep_one(manifest_text) or "")

            # (11a) the ride-along PNG does NOT inflate the requested-artifact count.
            check("export.files_included_requested_only",
                  manifest.get("files_included") == 2, str(manifest.get("files_included")))

        # (11b) a pilot-PNG-only job with the requested artifact absent still 404s —
        # the PNG can never satisfy the requested-artifact gate by itself.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            gate_job = _make_job(
                root, "job-gate", with_pdf=False,
                clean_md=produced,
                assets={ASSET: PNG_BYTES},
            )
            raised = False
            try:
                _bundle({"job-gate": gate_job}, ["job-gate"], ["pdf"])
            except HTTPException as exc:
                raised = exc.status_code == 404
            check("export.png_alone_does_not_satisfy_gate", raised)
    finally:
        _restore_env(old)


# ---------------------------------------------------------------------------
# Stage 4 — no-leak sweep over every serialized output (verification 13)
# ---------------------------------------------------------------------------
def _sweep_one(text: str) -> str | None:
    for label, pat in _LEAK_PATTERNS:
        if pat.search(text):
            return label
    return None


def stage_leak_sweep() -> None:
    leaks: list[str] = []
    for blob in OUTPUTS:
        found = _sweep_one(blob)
        if found is not None:
            leaks.append(found)
    check("sweep.no_leaks_in_any_output", not leaks, ",".join(sorted(set(leaks))))
    check("sweep.had_outputs_to_scan", len(OUTPUTS) > 0, str(len(OUTPUTS)))


def main() -> int:
    with tempfile.TemporaryDirectory() as d:
        work = Path(d)
        stage_insertion(work)
        stage_render(work)
    stage_export()
    stage_leak_sweep()
    print(f"\n{PASS} passed, {FAIL} failed, {SKIP} skipped")
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
